---
# URL: my-app.example.com              # Use --set in helm-install.sh for better security

# INGRESS_SECRET_NAME: tls-secret      # Use --set in helm-install.sh for better security

# OAUTH2_PROXY_CLIENT_ID: 12345        # Use --set in helm-install.sh for better security

# OAUTH2_PROXY_CLIENT_SECRET: 12345678 # Use --set in helm-install.sh for better security

# OAUTH2_PROXY_COOKIE_SECRET: 87654321 # Use --set in helm-install.sh for better security

# AUTHENTICATED_EMAILS:                 
#   - user1@company.tld
