{{ if (.Values.AUTHENTICATED_EMAILS) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: authenticated-emails-secret
type: Opaque
data:
  emails: |-
{{- range .Values.AUTHENTICATED_EMAILS }}
{{ .  | nindent 4 }}
{{- end}}
{{ end }}
