{{ if (.Values.AUTHENTICATED_EMAILS) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: authenticated-emails-configmap
data:
  emails: |
{{- range .Values.Secret1 }}
{{ .  | nindent 4 }}
{{- end}}
{{ end }}
