apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.{{ .Release.Name }}.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.url }}/oauth2/start?rd=$escaped_request_uri"
  name: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: {{ .Values.ingressSecretName }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy
          servicePort: 4180
        path: /oauth2
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: {{ .Values.ingressSecretName }}
