---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        timestamp: '{{ date "20060102150405" .Release.Time }}'
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: alpine:3.12.3
        ports:
        - containerPort: 80
        command:
        - "sh"
        - "-c"
        - |
          while true; do 
              echo -e "HTTP/1.1 200 OK\n\n $(date)"| nc -l -p 80
          done
---
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Release.Name }}
    port: 80
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
